name: Backend Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

env:
  NODE_OPTIONS: --max-old-space-size=5500

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'

    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: |
          ./cache
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

  test_suite:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run:  build/bk-build.sh test
