name: container-push-base-images-develop

on:
  push:
    branches:
      - develop
      - feature/INT-2909-create-gh-actions-build-themed-stratos
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: 'Log into GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: anynines
          password: ${{secrets.PKG_ACCESS_TOKEN}}
      - name: 'Checkout current develop'
        uses: actions/checkout@v3
        with:
          ref: "develop"
      - name: 'Build stratos base images'
        run: |
          docker login -u anynines -p ${{secrets.PKG_ACCESS_TOKEN}}
          ./deploy/stratos-base-images/build-base-images.sh -r ghcr.io -o anynines -p