name: container-push-base-images-develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          './stratos'
    steps:
      - name: 'Checkout current develop'
        uses: actions/checkout@develop
      
      - name: 'Log into GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build stratos base images'
        run: |
          ./deploy/stratos-base-images/build-base-images.sh -r ghcr.io -o anynines -p